apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cicd-run-
spec:
  pipelineRef:
    name: cicd-pipeline

  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: oc-pipelines-console-pvc